#---Schema---

schema {

    query: Query
    mutation: Mutation

}

#---Basis---

type Query {

    user: [UserResult]!
    detector: [DetectorResult]!
    prediction: [PredictionResult]!

}

type Mutation {

    add_user(user: User): UserResult!
    delete_user(user_id: String!): UserResult!
    update_user(user: User): UserResult!
}

#---Results---

type DeletionResult {

    success: Boolean!
    errors: [String]
}

type UserResult {

    success: Boolean!
    errors: [String]
    user: User

}

type DetectorResult {

    success: Boolean!
    errors: [String]
    user: User

}

type PredictionResult {

    success: Boolean!
    errors: [String]
    user: User

}

# ---Tables---

type User {
    
    user_id: String!
    email: String!
    
    detectors: [Detector]
    predictions: [Prediction]
    

}

type Detector {

    user_id: String!
    detector_id: Int!
    detector_name: String!

}

type Prediction {

    user_id: String!
    prediction_id: Int!

    is_valid: Boolean!
    sample_set: [Sample]!

}

# ---Custom Types---

type Sample {

    coordinates: Coordinate!
    climate: Climate!

}

type Coordinate {

    longitude: Float!
    latitude: Float!

}

type Climate {

    temperature: Float!
    barametric_pressure: Float!
    altitude: Float!

}
